### ISSUE TITLE
Meaning of currMat.datamat.depth

### ISSUE THREAD

**Issue by ghost** [aimerykong/Recurrent-Scene-Parsing-with-Perspective-Understanding-in-the-loop#2]
Hi Shu Kong:

I am reading the NYUv2 training script. I am wondering what does currMat.datamat.depth mean? Is it the dense depth value in the unit of mm? That is, the "depths" field of "nyu_depth_v2_labeled.mat" multiplied by 1000?

Thanks and Regards,

Yours, Dang Kang

**Comment by aimerykong** [comment]
Hi, Dang,

Yes, it is the depth map provided by the dataset, the raw depth map. While
I didn't check carefully what the values mean, I just imagine the depth map
from kinect camera records distance measured by mm.

I've uploaded three mat files (
https://github.com/aimerykong/Recurrent-Scene-Parsing-with-Perspective-Understanding-in-the-loop/tree/master/depthSegRNN_NYUv2/sampleMatFiles)
and modified the demo script. You can run demo_NYUv2.m
<https://github.com/aimerykong/Recurrent-Scene-Parsing-with-Perspective-Understanding-in-the-loop/blob/master/depthSegRNN_NYUv2/demo_NYUv2.m>
again
to see how these maps look like.

Regards,
Shu

**Comment by ghost** [comment]
Hi, Shu:

Thanks very much for the help. It is really nice and I appreciate that.
Will check it soon.

BTW. This year I have attended ICRA 2017 conference, and have noticed
noticed one paper a bit similar to your work.  However, that paper does not
perform experiments on semantic segmentation tasks. I attach it in the
email in case you are interested.

[5104-3223.pdf](https://github.com/aimerykong/Recurrent-Scene-Parsing-with-Perspective-Understanding-in-the-loop/files/1068466/5104-3223.pdf)

Thanks and Regards,

Yours, Dang.

**Comment by aimerykong** [comment]
Hi, Dang,

Thanks you for the information that there is a similar paper. But I am
afraid you didn't attach the paper:)

Regards,
Shu

**Comment by ghost** [comment]
Hi Shu:

I guess github somewhat removed the Email attachment.  I uploaded it here and please check.

https://github.com/aimerykong/Recurrent-Scene-Parsing-with-Perspective-Understanding-in-the-loop/files/1068466/5104-3223.pdf

Best Regards,

Yours, Dang Kang.

**Comment by aimerykong** [comment]
Hi, Dang,

Thank you for the link!

Yes, it looks very similar to the depth-aware gating module. Good to know
people in robotics field also pay attention to how to use the depth
information more effectively:)

Regards,
Shu
