### ISSUE TITLE
load Cityscapes_softmax_net-epoch-7.mat error

### ISSUE THREAD

**Issue by Fanpanda** [aimerykong/Recurrent-Scene-Parsing-with-Perspective-Understanding-in-the-loop#4]
I download Cityscapes_softmax_net-epoch-7.mat this model. But when I use Matlab load it, it is wrong.
![qq 20170708231255](https://user-images.githubusercontent.com/30004032/27986681-96af539e-6434-11e7-8c77-63790ea6338b.png)

**Comment by aimerykong** [comment]
Hi, I don't know what happens at your end. Perhaps the path is incorrect or even there is an issue with your matlab? Can you load NYU model, or some other mat files?

**Comment by Fanpanda** [comment]
Hi, I can load NYU model and any other mat files. I redownload Cityscapes_softmax_net-epoch-7.mat three times, but it dosen't work. My matlab version is 2014a.  And I use my friend matlab that it is also wrong.

**Comment by aimerykong** [comment]
![image](https://user-images.githubusercontent.com/6461732/27996244-db74e7f6-6492-11e7-9f97-defe20de1adc.png)

![image](https://user-images.githubusercontent.com/6461732/27996283-b6fb39c4-6493-11e7-87b9-6d095e93da68.png)

Hi, I double checked as you can see -- downloading the model from the google drive, using two different matlab version under ubuntu and windows -- I have no problem loading it; other folks raising questions do not have problems in loading it either. So, sorry I can't troubleshoot what's going on there.

**Comment by Fanpanda** [comment]
Thanks all the same.

**Comment by xjlnuc** [comment]
hi，fan
Did you solve the problem? I have encountered the same problem
