### ISSUE TITLE
run demo_cityscapes error, help, thanks

### ISSUE THREAD

**Issue by fireflychh** [aimerykong/Recurrent-Scene-Parsing-with-Perspective-Understanding-in-the-loop#5]
when I run the demo_cityscapes,thers is a error, I didn't use the matconvnet before, so I don't know what happend, help me, thanks. error is:
Error using vl_nnconv
An input is not a numeric array (or GPU support not compiled).

Error in dagnn.Conv/forward (line 11)
      outputs{1} = vl_nnconv(...

Error in dagnn.Layer/forwardAdvanced (line 85)
      outputs = obj.forward(inputs, {net.params(par).value}) ;

Error in dagnn.DagNN/eval (line 104)
    obj.layers(l).block.forwardAdvanced(obj.layers(l)) ;

Error in demo_Cityscapes (line 177)
    netMat.eval(inputs) ;

**Comment by aimerykong** [comment]
Hi,

I guess you didn't compile the gpu version of matconvnet.
Can you try to do this following the guide here (
http://www.vlfeat.org/matconvnet/install/) Basically you may just neet to
vl_compilenn('enableGpu', true)

Hope this helps:)
