### ISSUE TITLE
  run train_Cityscapes.m error,help,thanks

### ISSUE THREAD

**Issue by xjlnuc** [aimerykong/Recurrent-Scene-Parsing-with-Perspective-Understanding-in-the-loop#6]
Hi Shu Kong:
1.when I run the demo_cityscapes、train_Cityscapes.m、demo_NYUv2.m and train_NYUv2.m,thers is the same error, I have compile the gpu version of matconvnet.so I don't know what happend, help me, thanks. error is:
错误使用 gpuDevice (line 26)
Invalid CUDA device id: 2（or 3）. Select a device id from the range 1:1.
出错 train_Cityscapes (line 25)
gpuDevice(gpuId);
2.I have another questions,if i must donwload  [google drive] and where should i download the NYUv2 dataset、Cityscapes dataset?
That’s all,thank you!

**Comment by aimerykong** [comment]
Hi, it seems that you use the wrong GPU? Try gpuDevice(1) if you only have
one gpu?

For datasets, you can search NYUv2 and cityscapes and go to their website
to download. Each dataset has its own instruction, so it's better for you
to go through them.

Hope this helps!
